"""ImageMM: joint multi-frame image restoration and super-resolution.

Implementation of Sukurdeep, Budavári, Connolly & Navarro (2025), "ImageMM: Joint
Multi-Frame Image Restoration and Super-Resolution", arXiv:2501.03002 (v3).
Equation / algorithm numbers refer to the paper; verification against its own
model: experiments/test_imagemm.py.

Data (Sec. 2): n coregistered, background-subtracted exposures y(t) with
per-pixel variances v(t), binary masks m(t) and PSFs f(t) measured from their
stars (prepared from the raw subs by astrophoto/exposures.py).  Model (Eq. 1, 10):

    y(t)_i = (D (h(t) * x))_i + eta(t)_i,    eta(t)_i ~ N(0, v(t)_i),    x >= 0

x is the latent sky (sky = 0, sources > 0), padded so that every exposure pixel
is fully modelled: r(d + d') - 1 pixels per axis for d exposure pixels and PSFs
of d' pixels (d + d' - 1 without super-resolution); "*" is the valid
convolution; D is r x r average pooling and D^T subdivides every entry into
r x r replicas (Algorithm 2 remark).  Without super-resolution h(t) = f(t).

Algorithms 1 / 2 (Eqs. 7-9):

    u_k  = sum_t H(t)^T D^T W(t) y(t) / sum_t H(t)^T D^T W(t) D H(t) x_{k-1},    W(t) = diag(m(t) / v(t))
    u'_k = max(1/kappa, min(kappa, u_k)),    x_k = x_{k-1} * u'_k

Algorithm 3 (Eqs. 13-18): W(t) becomes m / v * psi(r) with the residuals
r = (y - D H x) / sigma recomputed every iteration and psi(z) = rho'(z)/z of the
Huber loss (Eq. 15, delta = 2).

x0 (Sec. 4.1): the median of the exposures, padded, non-positive values
replaced by a positive one; kappa = 2.  Stop (Appendix C, Eq. C15) when
|(1/M~) sum_i (m~ xi_k)_i - 1| < epsilon with xi_k = u'_k / u'_{k-1} and the
effective mask m~ = [(1/n) sum_t H^T D^T m(t) > mu], mu = 0.1, epsilon in
(1e-6, 1e-4); K is the maximum number of iterations.

Super-resolved PSFs (Eq. 11, Algorithm 2 lines 4-6): h(t) minimises
(1/d') sum_i (f(t)_i - (D(h * g_sigma))_i)^2, unconstrained, by Adam, with g_sigma
a centred Gaussian (2 r d' - 1 pixels per axis) generated by Monte Carlo
integration.

Like the paper (Sec. 5.1), the field is processed in cutouts; here they overlap
and are blended.

Optional, not part of the paper, each implemented to its own reference:
* Biggs & Andrews (1997) vector extrapolation of the multiplicative iteration
  (``BiggsAndrews``);
* seeing groups: inverse-variance coadds of exposures of similar PSF, each a
  single exposure of the same model with the weight-averaged PSF
  (``coadd_groups``);
* Moffat PSF models fitted to the empirical PSFs (exposures.fit_moffat).
"""
from __future__ import annotations

import math
import time

import numpy as np
import torch
import torch.nn.functional as F

from .denoise import _edge_weights, pick_device


# ----------------------------------------------------------------- PSFs
def gaussian_psf_mc(sigma: float, size: int, n_samples: int = 200_000_000, seed: int = 0,
                    chunk: int = 10_000_000) -> np.ndarray:
    """g_sigma of Algorithm 2 (line 4): a centred Gaussian PSF with standard deviation
    ``sigma`` (latent pixels) on a size x size grid (size odd), generated by Monte Carlo
    integration: every pixel holds the fraction of samples of N(0, sigma^2 I) that fall
    inside it (pixel j covers [j - c - 1/2, j - c + 1/2) around the centre c)."""
    assert size % 2 == 1
    rng = np.random.default_rng(seed)
    c = size // 2
    counts = np.zeros(size * size, np.int64)
    left = n_samples
    while left > 0:
        k = min(chunk, left)
        ij = np.floor(rng.normal(0.0, sigma, size=(k, 2)) + 0.5).astype(np.int64) + c
        ok = (ij >= 0).all(1) & (ij < size).all(1)
        counts += np.bincount(ij[ok, 0] * size + ij[ok, 1], minlength=size * size)
        left -= k
    g = counts.reshape(size, size).astype(np.float64)
    return (g / g.sum()).astype(np.float32)


def refine_psf(f: np.ndarray, up: int, sigma: float, g: np.ndarray | None = None, lr: float = 1e-3,
               max_iters: int = 200_000, rel_tol: float = 1e-8, device=None) -> tuple[np.ndarray, float]:
    """Super-resolved PSF h of Eq. 11 (Algorithm 2, line 6):

        h = argmin_{h in R^{r d'}} (1/d') sum_i (f_i - (D(h * g_sigma))_i)^2

    f: target PSF (d' x d', d' odd); h: r d' x r d'; g_sigma: (2 r d' - 1) x (2 r d' - 1);
    "h * g_sigma" is the valid convolution, of r d' x r d' pixels, and D is r x r average
    pooling.  Unconstrained, solved with Adam from f subdivided into r x r replicas.

    Eq. 11 has r^2 d'^2 unknowns for d'^2 equations, so its minimisers form an affine
    space, and once the loss is ~0 Adam's normalised steps keep moving h along it.  The
    iteration therefore stops as soon as the mean squared difference is below ``rel_tol``
    x mean(f^2) (the paper reports 3.9e-8 for its HSC PSFs, ~2e-4 relative), which leaves h
    at the minimiser reached from the smooth initial guess.
    Returns (h, final mean squared difference)."""
    h, mse = refine_psfs(f[None], up, sigma, g=g, lr=lr, max_iters=max_iters, rel_tol=rel_tol, device=device)
    return h[0], float(mse[0])


def refine_psfs(fs: np.ndarray, up: int, sigma: float, g: np.ndarray | None = None, lr: float = 1e-3,
                max_iters: int = 200_000, rel_tol: float = 1e-8, device=None) -> tuple[np.ndarray, np.ndarray]:
    """Eq. 11 (see ``refine_psf``) for many target PSFs at once: fs (N, d', d') -> h (N, r d', r d').

    The N problems are independent: each kernel's gradient comes only from its own loss and
    Adam's update is per parameter, so solving them together (one grouped convolution) gives
    every kernel exactly the iterates of a solve on its own.  Each kernel stops (is frozen)
    when its own mean squared difference falls below rel_tol x mean(f^2).
    Returns (h, per-kernel final mean squared difference)."""
    device = device or torch.device("cpu")
    N, n, _ = fs.shape
    m = up * n
    if g is None:
        g = gaussian_psf_mc(sigma, 2 * m - 1)
    ft = torch.from_numpy(np.ascontiguousarray(fs, np.float32)).to(device)
    gt = torch.from_numpy(np.ascontiguousarray(g, np.float32)).to(device)[None, None]
    scale = ft.abs().amax(dim=(1, 2)).view(N, 1, 1)
    # Adam's steps are ~lr per parameter; optimising z = h / max|f| makes the step lr * max|f|
    z = (unpool(ft[:, None], up)[:, 0] / up ** 2 / scale).clone().requires_grad_(True)
    opt = torch.optim.Adam([z], lr=lr)
    target = rel_tol * (ft ** 2).mean(dim=(1, 2))
    active = torch.ones(N, dtype=torch.bool, device=device)

    # every kernel correlates the same g_sigma: unfold its m x m patches once (im2col, as conv2d
    # evaluates a convolution) and apply all N flipped kernels as one matrix product
    cols = F.unfold(gt[:, :1], m)[0]                                   # (m^2, m^2) patches of g

    def model(zz):
        conv = ((zz * scale).flip(1, 2).reshape(N, m * m) @ cols).view(1, N, m, m)
        return pool(conv, up)[0]

    for it in range(max_iters):
        per = ((ft - model(z)) ** 2).mean(dim=(1, 2))
        with torch.no_grad():
            active &= per >= target
        if not bool(active.any()):
            break
        opt.zero_grad()
        (per * active).sum().backward()
        # a frozen kernel must not move at all (Adam would still step on its momentum)
        saved = z.detach()[~active].clone()
        opt.step()
        with torch.no_grad():
            z[~active] = saved
    with torch.no_grad():
        final = ((ft - model(z)) ** 2).mean(dim=(1, 2))
    return (z * scale).detach().cpu().numpy().astype(np.float32), final.cpu().numpy()


def _fwhm(k: np.ndarray) -> float:
    """FWHM of a centred PSF from its half-light radius (exact for a Gaussian)."""
    n = k.shape[-1]
    yy, xx = np.mgrid[:n, :n] - n // 2
    r = np.hypot(yy, xx).ravel()
    o = np.argsort(r)
    c = np.cumsum(k.ravel()[o]) / k.sum()
    return float(2 * r[o][np.searchsorted(c, 0.5)])


# ----------------------------------------------------------------- MM core
def pool(z: torch.Tensor, r: int) -> torch.Tensor:
    """D: r x r average pooling."""
    return z if r == 1 else F.avg_pool2d(z, r)


def unpool(z: torch.Tensor, r: int) -> torch.Tensor:
    """D^T as the paper defines it (Algorithm 2 remark): every entry subdivided into
    r x r replicas."""
    return z if r == 1 else z.repeat_interleave(r, -2).repeat_interleave(r, -1)


def huber_psi(z: torch.Tensor, delta: float) -> torch.Tensor:
    """psi(z) = rho'(z) / z (Eq. 18) of the Huber loss H_delta (Eq. 15): 1 for |z| <= delta,
    delta / |z| otherwise."""
    a = z.abs()
    return torch.where(a <= delta, torch.ones_like(z), delta / a.clamp_min(1e-30))


def latent_shape(h: int, w: int, ks: int, r: int) -> tuple[int, int]:
    """Latent size per axis for d exposure pixels and kernels of ks = r d' latent pixels:
    r(d + d') - 1 (Sec. 4.2; d + d' - 1 for r = 1, Sec. 3.1).  The valid convolution
    with the kernel maps it to r d pixels, which D pools to d."""
    return r * h + ks - 1, r * w + ks - 1


def exposure_origin(ks: int, r: int) -> float:
    """Latent coordinate of the centre of exposure pixel 0; exposure pixel i is centred at
    latent r i + this.  (Output j of the valid convolution is the kernel window centred at
    latent j + (ks - 1)/2, and D averages outputs r i ... r i + r - 1.)"""
    return (ks - 1) / 2 + (r - 1) / 2


def free_device_memory(device: torch.device) -> float | None:
    """Bytes this process can still allocate on ``device`` (None: no limit known, CPU)."""
    if device.type == "cuda":
        free, _ = torch.cuda.mem_get_info(device)
        # memory PyTorch has reserved but not handed out is available to this process too
        return float(free + torch.cuda.memory_reserved(device) - torch.cuda.memory_allocated(device))
    if device.type == "mps":
        try:
            return float(torch.mps.recommended_max_memory() - torch.mps.driver_allocated_memory())
        except Exception:
            return None
    return None


# per exposure, per channel and pixel of a cutout, mm_restore keeps y, v and the mask
# (3 arrays) and, for the exposures of one chunk, about 8 arrays of temporaries (forward
# model, residual, weights, their products, the im2col band buffers)
_PERSISTENT, _PER_CHUNK = 3, 8


def auto_chunk(n: int, C: int, d: int, device: torch.device, reserve: float = 0.85) -> int:
    """Exposures per chunk so that the temporaries of one chunk fit next to the persistent
    arrays.  The chunking only changes the order of the sums over exposures."""
    free = free_device_memory(device)
    if free is None:
        return n
    per = C * d * d * 4
    avail = reserve * free
    return int(max(1, min(n, avail // (_PER_CHUNK * per))))


class Operators:
    """H(t) (convolution of the padded latent with each exposure's kernel, valid part),
    D, and the adjoints H(t)^T and D^T, for a latent x of shape (1, C, X, Y).

    kernels: (n, C, k, k), one per exposure and channel.  The convolution is computed
    directly, as conv2d does it: im2col (``F.unfold``: every k x k latent patch as a
    column) times the matrix of all exposures' flipped kernels - the true convolution
    h * x, identical to conv2d (tests: experiments/test_imagemm.py).  The adjoint is the
    exact transpose: kernel matrix transposed times the residuals, then col2im
    (``F.fold``, which sums the overlapping patches).  One matrix product per channel
    covers every exposure; latent rows are processed in bands to bound memory."""

    def __init__(self, kernels: torch.Tensor, r: int = 1, chunk: int | None = None,
                 band_bytes: float = 512e6):
        self.n, self.C, self.ks, _ = kernels.shape
        self.r = r
        self.chunk = chunk or self.n
        # correlation weights of the true convolution: flipped kernels, (n, C, k*k)
        self.W = kernels.flip(-2, -1).reshape(self.n, self.C, self.ks * self.ks).contiguous()
        self.band_bytes = band_bytes

    def ranges(self):
        for a in range(0, self.n, self.chunk):
            yield a, min(a + self.chunk, self.n)

    def _band(self, width: int, m: int) -> int:
        """Output rows per band (a multiple of r): the im2col matrix (k^2 x rows*width) and
        the product (m x rows*width) must fit in ``band_bytes``."""
        per_row = 4 * width * (self.ks * self.ks + m)
        rows = max(self.r, int(self.band_bytes // per_row) // self.r * self.r)
        return rows

    def forward(self, x: torch.Tensor, a: int, b: int) -> torch.Tensor:
        """D H(t) x for exposures a..b-1 -> (b - a, C, d, d)."""
        m = b - a
        k = self.ks
        Hv, Wv = x.shape[-2] - k + 1, x.shape[-1] - k + 1          # valid output (r d x r d)
        out = torch.empty(m, self.C, Hv, Wv, device=x.device, dtype=x.dtype)
        band = self._band(Wv, m)
        for c in range(self.C):
            Wc = self.W[a:b, c]
            for r0 in range(0, Hv, band):
                r1 = min(r0 + band, Hv)
                cols = F.unfold(x[:, c:c + 1, r0:r1 + k - 1], k)[0]      # (k^2, rows * Wv)
                out[:, c, r0:r1] = (Wc @ cols).view(m, r1 - r0, Wv)
        return pool(out, self.r)

    def adjoint_sum(self, z: torch.Tensor, a: int, b: int) -> torch.Tensor:
        """sum_t H(t)^T D^T z(t) over exposures a..b-1; z (b - a, C, d, d) -> (1, C, X, Y)."""
        m = b - a
        k = self.ks
        zu = unpool(z, self.r)                                           # (m, C, r d, r d)
        Hv, Wv = zu.shape[-2:]
        X, Y = Hv + k - 1, Wv + k - 1
        out = torch.zeros(1, self.C, X, Y, device=z.device, dtype=z.dtype)
        band = self._band(Wv, m)
        for c in range(self.C):
            WcT = self.W[a:b, c].T                                       # (k^2, m)
            for r0 in range(0, Hv, band):
                r1 = min(r0 + band, Hv)
                cols = WcT @ zu[:, c, r0:r1].reshape(m, -1)              # (k^2, rows * Wv)
                out[0, c, r0:r1 + k - 1] += F.fold(cols[None], (r1 - r0 + k - 1, Y), k)[0, 0]
        return out


class BiggsAndrews:
    """Vector extrapolation of Biggs & Andrews (1997, Appl. Opt. 36, 1766), eqs. (11)-(15):
    the standard accelerator for multiplicative (Richardson-Lucy type) iterations.  Not
    part of ImageMM; optional.

        y_k = x_k + alpha_k h_k,          h_k = x_k - x_{k-1}
        x_{k+1} = psi(y_k)                (one ImageMM update from y_k)
        g_k = x_{k+1} - y_k
        alpha_k = sum(g_{k-1} g_{k-2}) / sum(g_{k-2} g_{k-2}),   0 <= alpha_k < 1

    The extrapolated point is kept strictly positive (the MM update needs x > 0)."""

    def __init__(self, floor: float):
        self.floor = floor
        self.x_prev = self.g1 = self.g2 = None
        self.alpha = 0.0

    def extrapolate(self, x: torch.Tensor) -> torch.Tensor:
        self.alpha = 0.0
        if self.g2 is not None and self.x_prev is not None:
            a = float((self.g1 * self.g2).sum() / (self.g2 * self.g2).sum().clamp_min(1e-30))
            self.alpha = min(max(a, 0.0), 0.999)
        if self.alpha == 0.0:
            return x
        return (x + self.alpha * (x - self.x_prev)).clamp_min(self.floor)

    def update(self, x: torch.Tensor, y: torch.Tensor, x_new: torch.Tensor):
        self.g2, self.g1 = self.g1, x_new - y
        self.x_prev = x


@torch.no_grad()
def mm_restore(y: torch.Tensor, var: torch.Tensor, mask: torch.Tensor, kernels: torch.Tensor,
               x0: torch.Tensor, r: int = 1, kappa: float = 2.0, robust: bool = True, delta: float = 2.0,
               max_iters: int = 1000, epsilon: float = 1e-6, mu: float = 0.1, chunk: int | None = None,
               accelerate: bool = False, stop: str = "c15", log=None) -> tuple[torch.Tensor, dict]:
    """Algorithms 1-3 on one cutout.

    y, var, mask: (n, C, d, d) exposures y(t), variances v(t), masks m(t) in {0, 1};
    kernels: (n, C, ks, ks) PSFs on the latent grid (f(t), or h(t) of Eq. 11);
    x0: (1, C, X, Y), strictly positive, of ``latent_shape``.
    robust=True: Algorithm 3 with the Huber loss (delta); False: Algorithm 1 (r = 1) / 2.
    Stopping rule ``stop``: "c15" - Eq. C15, |mean over m~ of u'_k / u'_{k-1} - 1| < epsilon
    (the paper; a necessary condition for u'_k ~ u'_{k-1}: ratios above and below 1 can cancel
    in the mean); "elementwise" - mean over m~ of |u'_k / u'_{k-1} - 1| < epsilon (u'_k ~ u'_{k-1}
    pixel by pixel).  On M 27 (experiments/diag_convergence.py, inside the field) at
    epsilon = 1e-6 the first stops at 185 iterations (max 11 %, rms 0.5 % of the peak from
    the 1500-iteration solution, the maximum at the brightest star cores), the second at 784
    (max 3.5 %, rms 0.2 %).  Or after max_iters.
    Returns (x, info)."""
    n = y.shape[0]
    if chunk is None:
        chunk = auto_chunk(n, y.shape[1], y.shape[-1], y.device)
    ops = Operators(kernels, r, chunk)

    def W_(a, b):                       # W(t) = m(t) / v(t), per chunk (not stored for all exposures)
        return torch.where(mask[a:b] > 0, 1.0 / var[a:b].clamp_min(1e-30), torch.zeros_like(var[a:b]))
    # effective mask m~ of Eq. C15
    frac = torch.zeros_like(x0)
    for a, b in ops.ranges():
        frac += ops.adjoint_sum(mask[a:b], a, b)
    m_eff = (frac / n > mu).float()
    M_eff = float(m_eff.sum())
    num = None
    if not robust:                     # Eq. 8: the numerator does not depend on x
        num = torch.zeros_like(x0)
        for a, b in ops.ranges():
            num += ops.adjoint_sum(W_(a, b) * y[a:b], a, b)
    acc = BiggsAndrews(float(x0.min())) if accelerate else None
    if accelerate:
        # extrapolated steps bring the mean of u'_k / u'_{k-1} to 1 about 100x sooner relative
        # to the true convergence (measured against a 20000-iteration run, experiments/
        # diag_accel.py): at epsilon / 100 the accelerated result is closer to the fixed point
        # than the plain run stopped at epsilon
        epsilon = epsilon / 100
    x = x0.clone()
    u_prev, hist, converged, k = None, [], False, 0
    for k in range(1, max_iters + 1):
        xe = acc.extrapolate(x) if acc is not None else x
        if robust:
            num = torch.zeros_like(x0)
        den = torch.zeros_like(x0)
        for a, b in ops.ranges():
            fx = ops.forward(xe, a, b)
            Wk = W_(a, b)
            if robust:                 # Eq. 17: W_rho = m / v * psi(r),  r = (y - D H x) / sigma  (Eq. 13)
                Wk = Wk * huber_psi((y[a:b] - fx) / var[a:b].clamp_min(1e-30).sqrt(), delta)
                num += ops.adjoint_sum(Wk * y[a:b], a, b)
            den += ops.adjoint_sum(Wk * fx, a, b)
            del fx, Wk
        u = torch.where(den > 0, num / den.clamp_min(1e-30), torch.ones_like(den))      # Eq. 8 / 16
        u = u.clamp(1.0 / kappa, kappa)                                                 # Eq. 9
        x_new = xe * u                                                                  # Eq. 7
        if acc is not None:
            acc.update(x, xe, x_new)
        x = x_new
        if u_prev is not None:
            xi = u / u_prev
            if stop == "c15":
                crit = abs(float((m_eff * xi).sum()) / max(M_eff, 1.0) - 1.0)            # Eq. C15
            else:
                crit = float((m_eff * (xi - 1).abs()).sum()) / max(M_eff, 1.0)
            hist.append(crit)
            if log:
                log(k, crit)
            if crit < epsilon:
                converged = True
                break
        u_prev = u
    return x, {"iterations": k, "converged": converged, "criterion": hist, "effective_mask": m_eff,
               "coverage": frac / n, "chunk": chunk}


def initial_guess(y: torch.Tensor, mask: torch.Tensor, ks: int, r: int = 1, how: str = "median",
                  floor: float | None = None) -> torch.Tensor:
    """x0 (Sec. 4.1): the median (or mean) of the exposures over their valid pixels, sampled
    at every latent pixel's position on the exposure grid (latent l <-> exposure
    (l - exposure_origin) / r; bilinear, edge values continued into the padding), with
    non-positive pixels replaced by ``floor`` (default 1e-3 x the robust noise level of
    the median image)."""
    # per-pixel statistic over the exposures, in row bands (a masked copy of all exposures at
    # once would double the memory of the cutout)
    n, C, h_, w_ = y.shape
    band = max(1, int(2 ** 26 // max(n * C * w_, 1)))
    med = torch.empty((1, C, h_, w_), device=y.device, dtype=y.dtype)
    for r0 in range(0, h_, band):
        yy = torch.where(mask[:, :, r0:r0 + band] > 0, y[:, :, r0:r0 + band], torch.full_like(y[:, :, r0:r0 + band], float("nan")))
        med[:, :, r0:r0 + band] = (torch.nanmedian(yy, dim=0, keepdim=True).values if how == "median"
                                   else torch.nanmean(yy, 0, keepdim=True))
    del yy
    med = torch.nan_to_num(med, nan=0.0)
    if floor is None:
        dev = 1.4826 * (med - med.median()).abs().median()
        floor = max(1e-3 * float(dev), 1e-12)
    h, w = med.shape[-2:]
    X, Y = latent_shape(h, w, ks, r)
    o = exposure_origin(ks, r)
    ey = (torch.arange(X, device=y.device, dtype=torch.float32) - o) / r
    ex = (torch.arange(Y, device=y.device, dtype=torch.float32) - o) / r
    # grid_sample, align_corners=True: -1 / +1 are the centres of the first / last pixel
    gy = (ey / max(h - 1, 1) * 2 - 1)[:, None].expand(X, Y)
    gx = (ex / max(w - 1, 1) * 2 - 1)[None, :].expand(X, Y)
    grid = torch.stack([gx, gy], -1)[None]
    x0 = F.grid_sample(med, grid, mode="bilinear", padding_mode="border", align_corners=True)
    return torch.where(x0 > 0, x0, torch.full_like(x0, floor))


# ----------------------------------------------------------------- seeing groups
def seeing_groups(kernels: np.ndarray, n_groups: int) -> list[np.ndarray]:
    """Split exposures into ``n_groups`` equal-count groups by PSF width (half-light
    diameter of the channel-averaged PSF), sharpest first."""
    fw = np.array([_fwhm(k.mean(0)) for k in kernels])
    order = np.argsort(fw, kind="stable")
    return [g for g in np.array_split(order, n_groups) if len(g)]


def coadd_groups(Y, V, Mk, K, groups):
    """Reduce every group of exposures to one exposure of the same model:

        y_g = sum_t w_t y_t / sum_t w_t,   v_g = 1 / sum_t w_t,   m_g = [sum_t w_t > 0],   w_t = m_t / v_t

    y_g = sum_t (w_t / sum w) (f_t * x) + noise, i.e. the PSF of the coadd is the weight-
    averaged member PSF; with the member weights' ratios uniform over the cutout that is
    f_g = sum_t W_t f_t / sum_t W_t with W_t the cutout-mean weight (per channel), exact
    when the members share one PSF.  The Huber weights of Algorithm 3 then act on the
    group residuals, so an outlier in one exposure is diluted by the group size."""
    n, C, h, w = Y.shape
    Yg, Vg, Mg, Kg = [], [], [], []
    for g in groups:
        wt = np.where(Mk[g] > 0, 1 / np.maximum(V[g], 1e-30), 0)
        sw = wt.sum(0)
        Yg.append(np.where(sw > 0, (wt * Y[g]).sum(0) / np.maximum(sw, 1e-30), 0))
        Vg.append(np.where(sw > 0, 1 / np.maximum(sw, 1e-30), 1.0))
        Mg.append((sw > 0).astype(np.float32))
        Wm = wt.mean((2, 3))                                  # (members, C)
        Kg.append((K[g] * Wm[:, :, None, None]).sum(0) / np.maximum(Wm.sum(0), 1e-30)[:, None, None])
    return (np.stack(Yg).astype(np.float32), np.stack(Vg).astype(np.float32), np.stack(Mg).astype(np.float32),
            np.stack(Kg).astype(np.float32))


# ----------------------------------------------------------------- one cutout of a session
def restore_cutout(es, y0: int, y1: int, x0: int, x1: int, idx: list[int] | None = None, r: int = 1,
                   kernels: np.ndarray | None = None, robust: bool = True, psf_model: str = "empirical",
                   n_groups: int = 0, device=None, **kw):
    """ImageMM (Algorithm 3 by default) of the prepared exposures ``es``
    (exposures.ExposureSet) on the reference-grid window [y0, y1) x [x0, x1).

    ``kernels``: latent-grid kernels for super-resolution (Eq. 11), aligned with ``idx``;
    default: the exposures' PSFs f(t) (``psf_model`` "empirical" or "moffat").
    ``n_groups`` > 0: seeing groups (``coadd_groups``) instead of every exposure.
    Returns (latent image cropped to the window on the latent grid, info)."""
    device = device or pick_device()
    idx = es.usable() if idx is None else idx
    Y, V, Mk = es.windows(idx, y0, y1, x0, x1)
    k = es.kernels(idx, psf_model) if kernels is None else kernels
    if n_groups:
        groups = seeing_groups(es.kernels(idx, psf_model), n_groups)
        Y, V, Mk, k = coadd_groups(Y, V, Mk, k, groups)
    yt, vt, mt = (torch.from_numpy(z).to(device) for z in (Y, V, Mk))
    kt = torch.from_numpy(k).to(device)
    ks = k.shape[-1]
    x0_ = initial_guess(yt, mt, ks, r)
    x, info = mm_restore(yt, vt, mt, kt, x0_, r=r, robust=robust, **kw)
    # output sample j sits at exposure coordinate j / r: latent index exposure_origin + j (an
    # integer for r = 1 with odd, and r = 2 with even, kernels)
    o = exposure_origin(ks, r)
    assert abs(o - round(o)) < 1e-9
    o = int(round(o))
    h, w = (y1 - y0) * r, (x1 - x0) * r
    out = x[0, :, o:o + h, o:o + w].permute(1, 2, 0).cpu().numpy()
    info["n_exposures"] = len(idx)
    info["psf_size"] = ks
    for key in ("effective_mask", "coverage"):
        info[key] = info[key][0, :, o:o + h, o:o + w].permute(1, 2, 0).cpu().numpy()
    return out, info


# ----------------------------------------------------------------- forward model on a stack grid
def lanczos_half_shift(z: torch.Tensor, a: int = 4) -> torch.Tensor:
    """Resample (..., H, W) at +1/2 pixel in both axes with a Lanczos-a kernel (2a taps,
    normalised): sample j of the output is z at j + 1/2.  Exact for band-limited signals up
    to the Lanczos window; the output loses a - 1/2 ... a pixels at the high edges (valid
    part only): (H - 2a + 1, W - 2a + 1), sample j at input coordinate j + a - 1/2."""
    t = torch.arange(-a + 1, a + 1, dtype=torch.float64) - 0.5            # tap offsets from the new sample
    wts = torch.sinc(t) * torch.sinc(t / a)
    wts = (wts / wts.sum()).to(z.dtype).to(z.device)
    zz = z.reshape(-1, 1, *z.shape[-2:])
    zz = F.conv2d(zz, wts.view(1, 1, 1, -1))
    zz = F.conv2d(zz, wts.view(1, 1, -1, 1))
    return zz.reshape(*z.shape[:-2], *zz.shape[-2:])


def stack_forward(x: torch.Tensor, kernels: torch.Tensor, s: int) -> tuple[torch.Tensor, float]:
    """Predicted exposure-grid images D H x for a patch x (B, C, P, P) of a stack grid at
    integer scale s whose pixel u is centred on reference coordinate (u + 1/2)/s - 1/2 (the
    drizzle convention of stacking.py) and whose origin is a multiple of s.

    kernels (G, C, k, k) on the stack grid (latent grid of ImageMM with r = s; for s = 1
    the exposure PSFs).  Returns (prediction (B, G, C, n, n), exposure-grid coordinate of
    prediction pixel 0 relative to the patch origin / s).

    s = 1: valid convolution; output j is exposure pixel j + (k-1)/2.
    s > 1 (k even, from Eq. 11): valid convolution, then - because ImageMM's latent pixels
    are co-sited with exposure pixel centres while drizzle pixels sit half a pixel off - a
    Lanczos-4 resampling by half a stack pixel (the PSF-blurred prediction is band-limited),
    then D (s x s average pooling)."""
    B, C, P, _ = x.shape
    G, _, k, _ = kernels.shape
    w = kernels.flip(-2, -1).reshape(G * C, 1, k, k)
    out = F.conv2d(x.repeat(1, G, 1, 1), w, groups=G * C)                   # (B, G*C, P-k+1, ...)
    if s == 1:
        return out.view(B, G, C, *out.shape[-2:]), (k - 1) / 2
    # valid output j is the kernel window centred at stack coordinate j + (k-1)/2 (a half-integer
    # for even k); after the half shift, sample j sits at stack coordinate c0 + j:
    out = lanczos_half_shift(out)
    c0 = (k - 1) / 2 + 4 - 0.5
    # exposure pixel i is centred at stack coordinate s i + (s-1)/2, i.e. it is the mean of the
    # s x s samples at stack coordinates s i ... s i + s - 1: pool blocks starting at a sample
    # whose stack coordinate is a multiple of s
    start = int(round((-c0) % s))
    out = out[..., start:, start:]
    n = min(out.shape[-2], out.shape[-1]) // s
    out = pool(out[..., :n * s, :n * s], s)
    e0 = (c0 + start) / s                          # exposure coordinate of pooled pixel 0
    return out.view(B, G, C, n, n), e0


# ----------------------------------------------------------------- Noise2Noise pass
def n2n_pass(xa: np.ndarray, xb: np.ndarray, iters: int = 2000, patch: int = 128, batch: int = 16,
             device=None, progress=None, cancel=None, seed: int = 0) -> tuple[np.ndarray, dict]:
    """Noise2Noise (Lehtinen et al. 2018) on two ImageMM restorations of disjoint sets of
    subs, whose noise is therefore independent.

    A network f is trained to minimise E w(x_A) |f(x_A) - x_B|^2 (and with A and B swapped).
    With x_B independent of x_A given the sky, the minimiser is E[x_B | x_A]; the loss is
    taken on the *linear* values (an L2 loss on transformed targets would give E[g(x_B)],
    biased for faint signal), and the weights w depend only on the input, so they change
    which errors dominate training but not the minimiser.  The network sees the inputs
    through u = asinh(x / (3 s)) and predicts in that domain, mapped back to linear values
    for the loss.  s: robust noise scale of (x_A - x_B)/sqrt 2 over pixels that carry signal
    (ImageMM's sky is ~0, so a scale over all pixels would vanish).
    Returns (1/2 (f(x_A) + f(x_B)), info)."""
    from .denoise import UNet, _autocast, infer
    device = device or pick_device()
    rng = np.random.default_rng(seed)
    torch.manual_seed(seed)
    C = xa.shape[2]
    s = np.zeros(C, np.float32)
    for c in range(C):
        a, b = xa[..., c], xb[..., c]
        sig = 0.5 * (a + b)
        on = sig > np.percentile(sig, 50)
        d = (a - b)[on]
        s[c] = 1.4826 * np.median(np.abs(d - np.median(d))) / np.sqrt(2)
    s = np.maximum(s, 1e-12)
    k = 3 * s
    fwd = lambda x: np.arcsinh(x / k).astype(np.float32)
    ua, ub = fwd(xa), fwd(xb)
    ta = torch.from_numpy(np.ascontiguousarray(np.moveaxis(xa, -1, 0)))
    tb = torch.from_numpy(np.ascontiguousarray(np.moveaxis(xb, -1, 0)))
    tua = torch.from_numpy(np.ascontiguousarray(np.moveaxis(ua, -1, 0)))
    tub = torch.from_numpy(np.ascontiguousarray(np.moveaxis(ub, -1, 0)))
    kt = torch.from_numpy(k).view(1, C, 1, 1).to(device)
    net = UNet(ch=C).to(device)
    opt = torch.optim.Adam(net.parameters(), lr=3e-4)
    sched = torch.optim.lr_scheduler.OneCycleLR(opt, max_lr=1e-3, total_steps=iters, pct_start=0.15)
    h, w = xa.shape[:2]
    t0 = time.time()
    for it in range(iters):
        if cancel and cancel():
            raise RuntimeError("cancelled")
        ys = rng.integers(0, h - patch, batch)
        xs = rng.integers(0, w - patch, batch)
        inp, tgt, lin_in = [], [], []
        for y0, x0, sw in zip(ys, xs, rng.random(batch) < 0.5):
            src = (tub, ta, tb) if sw else (tua, tb, ta)
            rot, fl = int(rng.integers(0, 4)), rng.random() < 0.5
            parts = []
            for z in src:
                q = torch.rot90(z[:, y0:y0 + patch, x0:x0 + patch], rot, (1, 2))
                parts.append(q.flip(2) if fl else q)
            inp.append(parts[0]), tgt.append(parts[1]), lin_in.append(parts[2])
        inp, tgt, lin_in = (torch.stack(z).to(device) for z in (inp, tgt, lin_in))
        with _autocast(device):
            u = net(inp)
        pred = torch.sinh(u.float()) * kt                       # linear prediction
        wgt = 1.0 / (1.0 + (lin_in / kt) ** 2)                   # depends on the input only
        loss = (wgt * (pred - tgt) ** 2).mean()
        opt.zero_grad(set_to_none=True)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(net.parameters(), 1.0)
        opt.step()
        sched.step()
        if progress and (it % 25 == 0 or it == iters - 1):
            progress(it + 1, iters, f"ImageMM Noise2Noise pass {it + 1}/{iters} ({time.time() - t0:.0f}s)")
    net.eval()
    tta = 8 if device.type != "cpu" else 2
    out = 0.5 * (np.sinh(infer(net, ua, tta=tta)) * k + np.sinh(infer(net, ub, tta=tta)) * k)
    return out.astype(np.float32), {"noise_scale": s.tolist(), "iters": iters}


# ----------------------------------------------------------------- full restoration
def superresolved_kernels(K: np.ndarray, r: int, sigma: float, device=None, progress=None):
    """Eq. 11 for every exposure and channel: (n, C, d', d') -> (n, C, r d', r d'), divided by r^2.

    With D the r x r *average*, D(h * g_sigma) = f makes h sum to r^2, and the latent x of
    D(h * x) is in flux per latent pixel (1/r^2 of the exposures' surface brightness).  The
    kernels h / r^2 describe exactly the same model for r^2 x, so with them the latent is in
    the exposures' (and the stack's) surface-brightness units - which the initial guess, the
    stack-grid forward model of the network and the pipeline all assume."""
    n, C, d, _ = K.shape
    if progress:
        progress(0, 1, f"ImageMM: solving Eq. 11 for {n * C} PSFs (r = {r}, sigma = {sigma})")
    h, mse = refine_psfs(K.reshape(n * C, d, d), r, sigma, device=device)
    return h.reshape(n, C, r * d, r * d) / r ** 2, mse


def restore(es, r: int = 1, sigma: float | None = None, psf_model: str = "empirical", n_groups: int = 0,
            robust: bool = True, delta: float = 2.0, kappa: float = 2.0, epsilon: float = 1e-6,
            max_iters: int = 1000, accelerate: bool = False, stop: str = "c15", tile: int = 384, device: str = "auto",
            n2n: bool = False, n2n_iters: int = 2000, progress=None, cancel=None) -> tuple[np.ndarray, dict]:
    """ImageMM over the whole field of the prepared exposures ``es`` (exposures.ExposureSet).

    r = 1 and sigma None: Algorithm 1 (robust=False) / 3 (robust=True) with the measured
    PSFs f(t).  r > 1, or a sigma: Algorithm 2 with the Eq. 11 kernels (the paper uses
    sigma = 1.1 for r = 2 and sigma = 1 for r = 1; default here 1.1 when r > 1).
    The field is restored in overlapping cutouts, as the paper processes cutouts; each is a
    complete ImageMM problem with its own padded latent (so flux from just outside the
    cutout is modelled) and its own Eq. C15 stop.  Cutouts overlap by at least two kernel
    widths and are blended with feathered weights.
    ``n2n``: restore the even and the odd subs separately (disjoint data, independent noise)
    and combine them with ``n2n_pass`` instead of restoring all subs at once.
    Returns (latent image on the r x finer grid - sample j at reference coordinate j / r -,
    info with the coverage map and per-cutout convergence)."""
    dev = device if isinstance(device, torch.device) else pick_device(device)
    t0 = time.time()
    idx = es.usable()
    K = es.kernels(idx, psf_model)
    kern, eq11 = None, None
    if r > 1 or sigma is not None:
        sigma = 1.1 if sigma is None else sigma
        kern, mse = superresolved_kernels(K, r, sigma, device=dev, progress=progress)
        eq11 = {"sigma": sigma, "mse_max": float(mse.max()), "mse_median": float(np.median(mse))}
    ks = (kern if kern is not None else K).shape[-1]
    H0, W0 = es.H0, es.W0
    overlap = int(max(64, 2 * math.ceil(ks / r)))
    tile = max(tile, 3 * overlap)
    # the exposures of a cutout (y, v, mask) must fit on the device next to at least one
    # exposure's temporaries; otherwise use smaller cutouts (same overlap, so the same result
    # up to the blending of more seams - see test_tiling in experiments/test_imagemm.py)
    free = free_device_memory(dev)
    n_exp = len(idx) if not n2n else (len(idx) + 1) // 2
    n_exp = min(n_exp, n_groups) if n_groups else n_exp
    if free is not None:
        def need(t):              # bytes: exposures of the cutout + one chunk + ~12 latent-size arrays
            return 4 * 3 * t * t * (_PERSISTENT * n_exp + _PER_CHUNK) + 4 * 3 * (t * r + ks) ** 2 * 12
        while tile > 3 * overlap and need(tile) > 0.85 * free:
            tile = max(3 * overlap, int(tile * 0.85))
        if need(tile) > 0.85 * free:
            raise RuntimeError(
                f"not enough {dev.type.upper()} memory for ImageMM: {free / 2**30:.2f} GiB free, one "
                f"{tile} px cutout of {n_exp} exposures needs {need(tile) / 2**30:.2f} GiB. Another process may be "
                f"holding GPU memory (check nvidia-smi), or use seeing groups / another device.")
    step = tile - overlap
    ys = sorted({min(y, max(H0 - tile, 0)) for y in range(0, max(H0 - overlap, 1), step)})
    xs = sorted({min(x, max(W0 - tile, 0)) for x in range(0, max(W0 - overlap, 1), step)})
    sets = [np.arange(len(idx))] if not n2n else [np.arange(0, len(idx), 2), np.arange(1, len(idx), 2)]
    outs, tiles = [], []
    cov = np.zeros((H0 * r, W0 * r, 3), np.float32)
    ntot = len(ys) * len(xs) * len(sets)
    for part, sel in enumerate(sets):
        sub_idx = [idx[i] for i in sel]
        sub_kern = kern[sel] if kern is not None else None
        out = np.zeros((H0 * r, W0 * r, 3), np.float32)
        acc = np.zeros((H0 * r, W0 * r, 1), np.float32)
        for y0 in ys:
            for x0 in xs:
                if cancel and cancel():
                    raise RuntimeError("cancelled")
                y1, x1 = min(y0 + tile, H0), min(x0 + tile, W0)
                x, info = restore_cutout(es, y0, y1, x0, x1, idx=sub_idx, r=r, kernels=sub_kern, robust=robust,
                                         psf_model=psf_model, n_groups=n_groups, device=dev, delta=delta,
                                         kappa=kappa, epsilon=epsilon, max_iters=max_iters, accelerate=accelerate,
                                         stop=stop)
                wy = _edge_weights((y1 - y0) * r, overlap * r, y0 > 0, y1 < H0)
                wx = _edge_weights((x1 - x0) * r, overlap * r, x0 > 0, x1 < W0)
                wgt = np.outer(wy, wx)[..., None]
                sl = (slice(y0 * r, y1 * r), slice(x0 * r, x1 * r))
                out[sl] += x * wgt
                cov[sl] += info["coverage"] * wgt / len(sets)
                acc[sl] += wgt
                tiles.append({"set": part, "window": [y0, y1, x0, x1], "iterations": info["iterations"],
                              "converged": info["converged"]})
                if progress:
                    done = len(tiles)
                    progress(done, ntot, f"ImageMM: cutout {done}/{ntot} "
                                         f"({info['iterations']} iterations, {time.time() - t0:.0f}s)")
        outs.append(out / np.maximum(acc, 1e-12))
        if part == 0:
            acc0 = acc
    cov /= np.maximum(acc0, 1e-12)
    n2n_info = None
    if n2n:
        out, n2n_info = n2n_pass(outs[0], outs[1], iters=n2n_iters, device=dev, progress=progress, cancel=cancel)
    else:
        out = outs[0]
    if dev.type == "mps":
        torch.mps.empty_cache()
    elif dev.type == "cuda":
        torch.cuda.empty_cache()
    return out, {"method": "ImageMM (arXiv:2501.03002), Algorithm " + ("2" if kern is not None else ("3" if robust else "1")),
                 "robust": robust, "delta": delta, "kappa": kappa, "epsilon": epsilon, "stop": stop, "r": r, "eq11": eq11,
                 "psf_model": psf_model, "n_groups": n_groups, "accelerate": accelerate, "n2n": n2n_info,
                 "n_exposures": len(idx), "psf_size": ks, "tiles": tiles, "coverage": cov,
                 "seconds": round(time.time() - t0, 1)}
